"""correct table colomns.

Revision ID: b7f6e62cc15f
Revises: fd7f4c7d45f1
Create Date: 2025-01-20 13:23:27.131257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7f6e62cc15f'
down_revision = 'fd7f4c7d45f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('surf_spot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direction', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('type', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('experience', sa.String(length=50), nullable=False))
        batch_op.drop_column('difficulty')
        batch_op.drop_column('location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('surf_spot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('difficulty', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_column('experience')
        batch_op.drop_column('type')
        batch_op.drop_column('direction')

    # ### end Alembic commands ###
